name: "FreeBSD build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 2'

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Test on FreeBSD 12.2
      uses: cross-platform-actions/action@v0.0.1
      with:
        operating_system: freebsd
        version: 12.2
        shell: bash
        run: |
          uname -a
          freebsd-version
          whoami
          pwd
          sudo pkg update
          sudo pkg install -y lang/gcc devel/autotools autotools automake autoconf autoconf-archive libtool pkgconf devel/ncurses devel/cppunit cppunit
          g++ --version
          autoreconf -v --install --force
          ./configure --prefix=/usr
          make -j10

