name: "macOS build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 2'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Before_install
      run: |
        uname -a
        g++ --version
        whoami
        pwd

    - name: Install dependencies via homebrew
      run: |
        brew update
        brew install automake
        brew install autoconf-archive

    - name: Build
      run: |
        autoreconf -v --install --force
        ./configure --prefix=/usr
        make -j10

